name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    if: "!contains(join(github.event.commits.*.message, ' '), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Aliyun Container Registry
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login --username ${{ secrets.ACR_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

      - name: Build Docker image
        run: docker build -t registry.cn-hangzhou.aliyuncs.com/daxx/sms-proxy:1.0.0 .

      - name: Push Docker image
        run: docker push registry.cn-hangzhou.aliyuncs.com/daxx/sms-proxy:1.0.0